# Per-language page metadata. Dict order is the order of the language switcher.
E = 'privacy-policy.html'

LANGS = {
    "en": dict(name="English", title="Privacy Policy - Compresso", note=""),
    "ar": dict(name="العربية", title="سياسة الخصوصية - Compresso", rtl=True,
               note=f'هذه ترجمة للنص الأصلي باللغة الإنجليزية. إذا اختلفت الترجمة عنه، فإن <a href="{E}">النسخة الإنجليزية</a> هي المعتمدة.'),
    "bg": dict(name="Български", title="Политика за поверителност - Compresso",
               note=f'Това е превод на английския оригинал. Ако двата текста се различават, предимство има <a href="{E}">английската версия</a>.'),
    "bn": dict(name="বাংলা", title="গোপনীয়তা নীতি - Compresso",
               note=f'এটি ইংরেজি মূল নথির অনুবাদ। দুটির মধ্যে পার্থক্য থাকলে <a href="{E}">ইংরেজি সংস্করণটি</a> প্রাধান্য পাবে।'),
    "ca": dict(name="Català", title="Política de privadesa - Compresso",
               note=f'Aquesta és una traducció de l\'original en anglès. Si hi ha diferències, preval la <a href="{E}">versió anglesa</a>.'),
    "cs": dict(name="Čeština", title="Zásady ochrany osobních údajů - Compresso",
               note=f'Toto je překlad anglického originálu. Pokud se od něj liší, platí <a href="{E}">anglická verze</a>.'),
    "da": dict(name="Dansk", title="Privatlivspolitik - Compresso",
               note=f'Dette er en oversættelse af den engelske original. Hvis de to afviger fra hinanden, har <a href="{E}">den engelske version</a> forrang.'),
    "de": dict(name="Deutsch", title="Datenschutzerklärung - Compresso",
               note=f'Dies ist eine Übersetzung des englischen Originals. Bei Abweichungen gilt die <a href="{E}">englische Fassung</a>.'),
    "el": dict(name="Ελληνικά", title="Πολιτική απορρήτου - Compresso",
               note=f'Αυτή είναι μετάφραση του αγγλικού πρωτοτύπου. Σε περίπτωση απόκλισης, υπερισχύει η <a href="{E}">αγγλική έκδοση</a>.'),
    "es": dict(name="Español", title="Política de privacidad - Compresso",
               note=f'Esta es una traducción del original en inglés. Si hay diferencias, prevalece la <a href="{E}">versión en inglés</a>.'),
    "et": dict(name="Eesti", title="Privaatsuspoliitika - Compresso",
               note=f'See on ingliskeelse originaali tõlge. Lahknevuse korral kehtib <a href="{E}">ingliskeelne versioon</a>.'),
    "fi": dict(name="Suomi", title="Tietosuojakäytäntö - Compresso",
               note=f'Tämä on käännös englanninkielisestä alkuperäisestä. Jos ne eroavat toisistaan, <a href="{E}">englanninkielinen versio</a> on ratkaiseva.'),
    "fr": dict(name="Français", title="Politique de confidentialité - Compresso",
               note=f'Ceci est une traduction de l\'original en anglais. En cas de divergence, la <a href="{E}">version anglaise</a> prévaut.'),
    "gu": dict(name="ગુજરાતી", title="ગોપનીયતા નીતિ - Compresso",
               note=f'આ અંગ્રેજી મૂળ દસ્તાવેજનો અનુવાદ છે. બંને વચ્ચે તફાવત હોય તો <a href="{E}">અંગ્રેજી સંસ્કરણ</a> માન્ય ગણાશે.'),
    "he": dict(name="עברית", title="מדיניות פרטיות - Compresso", rtl=True,
               note=f'זהו תרגום של המקור באנגלית. במקרה של סתירה, <a href="{E}">הגרסה האנגלית</a> היא הקובעת.'),
    "hi": dict(name="हिन्दी", title="गोपनीयता नीति - Compresso",
               note=f'यह अंग्रेज़ी मूल दस्तावेज़ का अनुवाद है। दोनों में अंतर होने पर <a href="{E}">अंग्रेज़ी संस्करण</a> मान्य होगा।'),
    "hr": dict(name="Hrvatski", title="Pravila privatnosti - Compresso",
               note=f'Ovo je prijevod engleskog izvornika. U slučaju razlika mjerodavna je <a href="{E}">engleska verzija</a>.'),
    "hu": dict(name="Magyar", title="Adatvédelmi irányelvek - Compresso",
               note=f'Ez az angol eredeti fordítása. Eltérés esetén az <a href="{E}">angol változat</a> az irányadó.'),
    "id": dict(name="Bahasa Indonesia", title="Kebijakan Privasi - Compresso",
               note=f'Ini adalah terjemahan dari dokumen asli berbahasa Inggris. Jika terdapat perbedaan, <a href="{E}">versi bahasa Inggris</a> yang berlaku.'),
    "it": dict(name="Italiano", title="Informativa sulla privacy - Compresso",
               note=f'Questa è una traduzione dell\'originale inglese. In caso di discrepanze prevale la <a href="{E}">versione inglese</a>.'),
    "ja": dict(name="日本語", title="プライバシーポリシー - Compresso",
               note=f'これは英語の原文の翻訳です。内容に相違がある場合は、<a href="{E}">英語版</a>が優先されます。'),
    "kn": dict(name="ಕನ್ನಡ", title="ಗೌಪ್ಯತಾ ನೀತಿ - Compresso",
               note=f'ಇದು ಇಂಗ್ಲಿಷ್ ಮೂಲ ದಾಖಲೆಯ ಅನುವಾದ. ಎರಡರ ನಡುವೆ ವ್ಯತ್ಯಾಸವಿದ್ದರೆ <a href="{E}">ಇಂಗ್ಲಿಷ್ ಆವೃತ್ತಿ</a> ಮಾನ್ಯವಾಗುತ್ತದೆ.'),
    "ko": dict(name="한국어", title="개인정보 처리방침 - Compresso",
               note=f'이 문서는 영어 원문의 번역본입니다. 내용이 서로 다를 경우 <a href="{E}">영어 원문</a>이 우선합니다.'),
    "lt": dict(name="Lietuvių", title="Privatumo politika - Compresso",
               note=f'Tai angliško originalo vertimas. Jei tekstai skiriasi, galioja <a href="{E}">angliška versija</a>.'),
    "lv": dict(name="Latviešu", title="Privātuma politika - Compresso",
               note=f'Šis ir angļu valodas oriģināla tulkojums. Ja teksti atšķiras, noteicošā ir <a href="{E}">angļu valodas versija</a>.'),
    "ml": dict(name="മലയാളം", title="സ്വകാര്യതാ നയം - Compresso",
               note=f'ഇത് ഇംഗ്ലീഷ് മൂലരേഖയുടെ വിവർത്തനമാണ്. രണ്ടും തമ്മിൽ വ്യത്യാസമുണ്ടെങ്കിൽ <a href="{E}">ഇംഗ്ലീഷ് പതിപ്പ്</a> ആണ് പ്രാബല്യത്തിൽ.'),
    "mr": dict(name="मराठी", title="गोपनीयता धोरण - Compresso",
               note=f'हे इंग्रजी मूळ दस्तऐवजाचे भाषांतर आहे. दोन्हींमध्ये फरक असल्यास <a href="{E}">इंग्रजी आवृत्ती</a> ग्राह्य धरली जाईल.'),
    "ms": dict(name="Bahasa Melayu", title="Dasar Privasi - Compresso",
               note=f'Ini ialah terjemahan dokumen asal dalam bahasa Inggeris. Jika terdapat perbezaan, <a href="{E}">versi bahasa Inggeris</a> akan terpakai.'),
    "nl": dict(name="Nederlands", title="Privacybeleid - Compresso",
               note=f'Dit is een vertaling van het Engelse origineel. Bij verschillen is de <a href="{E}">Engelse versie</a> leidend.'),
    "no": dict(name="Norsk", title="Personvernerklæring - Compresso",
               note=f'Dette er en oversettelse av den engelske originalen. Ved avvik gjelder <a href="{E}">den engelske versjonen</a>.'),
    "or": dict(name="ଓଡ଼ିଆ", title="ଗୋପନୀୟତା ନୀତି - Compresso",
               note=f'ଏହା ଇଂରାଜୀ ମୂଳ ଦଲିଲର ଅନୁବାଦ। ଦୁଇଟି ମଧ୍ୟରେ ପାର୍ଥକ୍ୟ ଥିଲେ <a href="{E}">ଇଂରାଜୀ ସଂସ୍କରଣ</a> ପ୍ରାଧାନ୍ୟ ପାଇବ।'),
    "pa": dict(name="ਪੰਜਾਬੀ", title="ਪਰਦੇਦਾਰੀ ਨੀਤੀ - Compresso",
               note=f'ਇਹ ਅੰਗਰੇਜ਼ੀ ਮੂਲ ਦਸਤਾਵੇਜ਼ ਦਾ ਅਨੁਵਾਦ ਹੈ। ਦੋਵਾਂ ਵਿੱਚ ਫ਼ਰਕ ਹੋਣ ’ਤੇ <a href="{E}">ਅੰਗਰੇਜ਼ੀ ਸੰਸਕਰਣ</a> ਮੰਨਿਆ ਜਾਵੇਗਾ।'),
    "pl": dict(name="Polski", title="Polityka prywatności - Compresso",
               note=f'To jest tłumaczenie angielskiego oryginału. W razie rozbieżności wiążąca jest <a href="{E}">wersja angielska</a>.'),
    "pt-BR": dict(name="Português (Brasil)", title="Política de Privacidade - Compresso",
                  note=f'Esta é uma tradução do original em inglês. Em caso de divergência, prevalece a <a href="{E}">versão em inglês</a>.'),
    "pt-PT": dict(name="Português (Portugal)", title="Política de Privacidade - Compresso",
                  note=f'Esta é uma tradução do original em inglês. Em caso de divergência, prevalece a <a href="{E}">versão inglesa</a>.'),
    "ro": dict(name="Română", title="Politica de confidențialitate - Compresso",
               note=f'Aceasta este o traducere a originalului în limba engleză. În caz de neconcordanță, prevalează <a href="{E}">versiunea în engleză</a>.'),
    "ru": dict(name="Русский", title="Политика конфиденциальности - Compresso",
               note=f'Это перевод английского оригинала. Если они расходятся, действует <a href="{E}">английская версия</a>.'),
    "sk": dict(name="Slovenčina", title="Zásady ochrany osobných údajov - Compresso",
               note=f'Toto je preklad anglického originálu. Ak sa od neho líši, platí <a href="{E}">anglická verzia</a>.'),
    "sl": dict(name="Slovenščina", title="Pravilnik o zasebnosti - Compresso",
               note=f'To je prevod angleškega izvirnika. Če se besedili razlikujeta, velja <a href="{E}">angleška različica</a>.'),
    "sv": dict(name="Svenska", title="Integritetspolicy - Compresso",
               note=f'Detta är en översättning av det engelska originalet. Vid avvikelser gäller <a href="{E}">den engelska versionen</a>.'),
    "ta": dict(name="தமிழ்", title="தனியுரிமைக் கொள்கை - Compresso",
               note=f'இது ஆங்கில மூல ஆவணத்தின் மொழிபெயர்ப்பு. இரண்டுக்கும் இடையே வேறுபாடு இருந்தால் <a href="{E}">ஆங்கிலப் பதிப்பே</a> செல்லுபடியாகும்.'),
    "te": dict(name="తెలుగు", title="గోప్యతా విధానం - Compresso",
               note=f'ఇది ఆంగ్ల మూల పత్రానికి అనువాదం. రెండింటి మధ్య తేడా ఉంటే <a href="{E}">ఆంగ్ల సంస్కరణ</a> చెల్లుబాటు అవుతుంది.'),
    "th": dict(name="ไทย", title="นโยบายความเป็นส่วนตัว - Compresso",
               note=f'นี่คือคำแปลจากต้นฉบับภาษาอังกฤษ หากเนื้อหาไม่ตรงกัน ให้ถือ<a href="{E}">ฉบับภาษาอังกฤษ</a>เป็นหลัก'),
    "tr": dict(name="Türkçe", title="Gizlilik Politikası - Compresso",
               note=f'Bu, İngilizce aslının çevirisidir. İkisi arasında fark olması durumunda <a href="{E}">İngilizce sürüm</a> geçerlidir.'),
    "uk": dict(name="Українська", title="Політика конфіденційності - Compresso",
               note=f'Це переклад англійського оригіналу. Якщо вони розходяться, чинною є <a href="{E}">англійська версія</a>.'),
    "ur": dict(name="اردو", title="رازداری کی پالیسی - Compresso", rtl=True,
               note=f'یہ انگریزی اصل دستاویز کا ترجمہ ہے۔ دونوں میں فرق ہونے کی صورت میں <a href="{E}">انگریزی ورژن</a> کو ترجیح حاصل ہوگی۔'),
    "vi": dict(name="Tiếng Việt", title="Chính sách quyền riêng tư - Compresso",
               note=f'Đây là bản dịch từ bản gốc tiếng Anh. Nếu có khác biệt, <a href="{E}">bản tiếng Anh</a> sẽ được ưu tiên áp dụng.'),
    "zh-Hans": dict(name="简体中文", title="隐私政策 - Compresso",
                    note=f'本文为英文原文的译本。如两者存在差异，以<a href="{E}">英文版本</a>为准。'),
    "zh-Hant": dict(name="繁體中文", title="隱私權政策 - Compresso",
                    note=f'本文為英文原文的譯本。如兩者有所出入，以<a href="{E}">英文版本</a>為準。'),
}
